title: "R Users Hamburg"
author: "rusershamburg"
description: "R Users Hamburg"
more: "... read more »"
url: "https://rusershamburg.github.io"
#baseurl: "/"
paginate: 10
paginate_path: blog/page:num
permalink: pretty
excerpt_separator: "\n\n\n" # two blank lines
plugins: [jekyll-feed, jekyll-paginate]

style:
  minimalist: false
  dark: false

navigation:
  - index.md
  - blog/index.html
  - archive.html

comments: 
  disqus: "https-rusershamburg-github-io"
#  isso: "comments.mysite.org"

links: # see http://fontawesome.io/icons/#brand for all possible icons
  - meetup: "https://www.meetup.com/Hamburg-R-User-Group/"
  - twitter: "https://twitter.com/rusershamburg"
  - github: "https://github.com/rusershamburg"

defaults: [
  {
    scope: {path: ""}, 
    values: {layout: "default"}
  }, 
  {
    scope: {path: "", type: "posts"}, 
    values: {comments: true}
    }
  ]
sass: {style: expanded}
exclude: [rmd_posts]

